defmodule Exoda.Types do
  @moduledoc """
  Module contains a part of implementation of `Ecto.Adapter` behaviour
  related to types convertion.
  """
  
  @doc """
  Returns the loaders for a given type.

  Is used to trasform types returned from http endpoint
  to ecto types

  It receives the primitive type and the Ecto type (which may be
  primitive as well). It returns a list of loaders with the given
  type at the end.

  """
  @spec loaders(primitive_type :: Ecto.Type.primitive(), ecto_type :: Ecto.Type.t()) :: [
          (term -> {:ok, term} | :error) | Ecto.Type.t()
        ]
  def loaders(:binary_id, type), do: [Ecto.UUID, type]
  def loaders(_primitive, type), do: [type]

  @doc """
  Returns the dumpers for a given type.

  It receives the primitive type and the Ecto type (which may be
  primitive as well). It returns a list of dumpers with the given
  type at the beginning.

  It is used to translate values coming from the Ecto into a http compliant types


  """
  @spec dumpers(primitive_type :: Ecto.Type.primitive(), ecto_type :: Ecto.Type.t()) :: [
          (term -> {:ok, term} | :error) | Ecto.Type.t()
        ]
  def dumpers(:binary_id, type), do: [type, Ecto.UUID]
  def dumpers(_primitive, type), do: [type]

  #
  ## Autogenerate

  @doc """
  Called to autogenerate a value for id/embed_id/binary_id.

  Returns nil because ids must be autogenerated inside the storage
  """
  @spec autogenerate(field_type :: :id | :binary_id | :embed_id) :: term | nil | no_return
  def autogenerate(:id), do: nil
  def autogenerate(:embed_id), do: Ecto.UUID.generate()
  def autogenerate(:binary_id), do: Ecto.UUID.autogenerate()
end
